name: Release to Charmhub

on:
  push:
    branches:
      - main

jobs:
  release-to-charmhub:
    name: Release to Charmhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.4.0
        id: channel

      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.4.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
