name: Static analysis

on:
  workflow_call:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static

