name: Static analysis

on:
  workflow_call:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e static

