name: TiCS Static Analysis

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 3 am
  workflow_dispatch: # Allows manual triggering

jobs:
  analyze-k8s:
    uses: canonical/identity-credentials-workflows/.github/workflows/tics-tox.yaml@v0
    with:
      project: vault-k8s-operator
      dir: k8s
    secrets:
      TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}

  analyze-machine:
    uses: canonical/identity-credentials-workflows/.github/workflows/tics-tox.yaml@v0
    with:
      project: vault-operator
      dir: machine
    secrets:
      TICSAUTHTOKEN: ${{ secrets.TICSAUTHTOKEN }}
