name: Scan UV dependencies

on:
  push:
    branches:
      - release-1.16

jobs:
  scan-k8s:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: canonical/identity-credentials-workflows/.github/workflows/uv-scan.yaml@v0
    with:
      uv-lock-path: "./k8s/uv.lock"
  scan-machine:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: canonical/identity-credentials-workflows/.github/workflows/uv-scan.yaml@v0
    with:
      uv-lock-path: "./machine/uv.lock"
