name: Scan UV dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  scan-k8s:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: canonical/identity-credentials-workflows/.github/workflows/uv-scan.yaml@v3.0.0
    with:
      path: ./k8s
  scan-machine:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: canonical/identity-credentials-workflows/.github/workflows/uv-scan.yaml@v3.0.0
    with:
      path: ./machine
